Importing the Dependecies

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

Data Collection and Analysis

PIMA Diabetes Dataset

In [2]:
# Loading the Diabetes dataset to a pandas DataFrame
diabetes_dataset = pd.read_csv('diabetes.csv')

print(diabetes_dataset.head())

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6
1            1       85             66             29        0  26.6
2            8      183             64              0        0  23.3
3            1       89             66             23       94  28.1
4            0      137             40             35      168  43.1

   DiabetesPedigreeFunction  Age  Outcome
0                     0.627   50        1
1                     0.351   31        0
2                     0.672   32        1
3                     0.167   21        0
4                     2.288   33        1

In [3]:
# Printing the first 5 rows of the dataset
diabetes_dataset.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
# number of rows and columns in the dataset 
diabetes_dataset.shape

(768, 9)

In [5]:
# Getting the stastical measures of the data 
diabetes_dataset.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.00000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.778646,69.097656,20.52474,79.799479,31.992057,0.472081,33.236979,0.348958
std,3.369578,32.013735,19.353423,15.94709,115.244002,7.884147,0.331359,11.756818,0.476951
min,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.00000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.00000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.000000,80.000000,32.00000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.00000,846.000000,67.100000,2.420000,81.000000,1.000000

In [6]:
diabetes_dataset['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

0 ---> Non Diabetic

1 ---> Diabetic

In [7]:
diabetes_dataset.groupby('Outcome').mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,3.298000,109.980000,68.184000,19.664000,68.792000,30.304200,0.429734,31.19000
1,4.865672,140.925373,70.802239,22.130597,100.335821,35.141045,0.551086,37.05597

In [8]:
diabetes_dataset.groupby('Outcome').median()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,2.0,107.0,70.0,21.0,39.0,30.05,0.3360,27.0
1,4.0,139.5,74.0,27.0,0.0,34.25,0.4515,36.0

In [9]:
# Separating the Data & Labels
X = diabetes_dataset.drop(columns='Outcome', axis=1)
Y = diabetes_dataset['Outcome']

In [10]:
print(X)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6
1              1       85             66             29        0  26.6
2              8      183             64              0        0  23.3
3              1       89             66             23       94  28.1
4              0      137             40             35      168  43.1
..           ...      ...            ...            ...      ...   ...
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
766            1      126             60              0        0  30.1
767            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age
0                       0.627   50
1                       0.351   31
2                       0.672   32
3                       0.167   21
4                       2.288   33
..                        ...  ...
763                     0.171   63
764                     0.340   27
765                     0.245   30
766                     0.349   47
767                     0.315   23

[768 rows x 8 columns]

In [11]:
print(Y)

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

Data Standardization

In [12]:
Scaler= StandardScaler()

In [13]:
Scaler.fit(X)

StandardScaler()

In [14]:
Standardized_data = Scaler.transform(X)

In [15]:
print(Standardized_data)

[[ 0.63994726  0.85085647  0.15006312 ...  0.20407923  0.46783139
   1.42674187]
 [-0.84488505 -1.1183313  -0.16016158 ... -0.68435703 -0.36564441
  -0.19039479]
 [ 1.23388019  1.94484968 -0.26356982 ... -1.10319127  0.60372418
  -0.10528233]
 ...
 [ 0.3429808   0.00691886  0.15006312 ... -0.73512482 -0.68574743
  -0.27550725]
 [-0.84488505  0.1632036  -0.47038629 ... -0.2401389  -0.37168409
   1.1714045 ]
 [-0.84488505 -0.86827571  0.04665489 ... -0.20206306 -0.47435864
  -0.87129444]]

In [16]:
X = Standardized_data
Y = diabetes_dataset['Outcome']

In [17]:
print(X)
print(Y)

[[ 0.63994726  0.85085647  0.15006312 ...  0.20407923  0.46783139
   1.42674187]
 [-0.84488505 -1.1183313  -0.16016158 ... -0.68435703 -0.36564441
  -0.19039479]
 [ 1.23388019  1.94484968 -0.26356982 ... -1.10319127  0.60372418
  -0.10528233]
 ...
 [ 0.3429808   0.00691886  0.15006312 ... -0.73512482 -0.68574743
  -0.27550725]
 [-0.84488505  0.1632036  -0.47038629 ... -0.2401389  -0.37168409
   1.1714045 ]
 [-0.84488505 -0.86827571  0.04665489 ... -0.20206306 -0.47435864
  -0.87129444]]
0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

Train Test Split

In [18]:
X_train , X_test , Y_train , Y_test = train_test_split(X,Y,test_size=0.2, stratify=Y,random_state=1)

In [19]:
print(X.shape, X_train.shape, X_test.shape)

(768, 8) (614, 8) (154, 8)

Tranning the Model

In [20]:
cassifier=svm.SVC(kernel='linear')

In [21]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import svm

# Load dataset
diabetes_dataset = pd.read_csv('diabetes.csv')

# Split data
X = diabetes_dataset.drop(columns='Outcome', axis=1)
Y = diabetes_dataset['Outcome']

# Train-test split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

# Create classifier
classifier = svm.SVC(kernel='linear')

# Train model
classifier.fit(X_train, Y_train)

SVC(kernel='linear')

Model Evaluation

Accuracy Score

In [22]:
from sklearn.metrics import accuracy_score

# prediction on training data
X_train_prediction = classifier.predict(X_train)

# accuracy calculation
training_data_accuracy = accuracy_score(Y_train, X_train_prediction)

print("Accuracy on training data:", training_data_accuracy)

Accuracy on training data: 0.7703583061889251

In [23]:
# accuracy score on the test data
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score(Y_test, X_test_prediction)

print("Accuracy on the test data:", test_data_accuracy)

Accuracy on the test data: 0.7532467532467533

Making a Predictive System

In [24]:
input_data = (4,110,92,0,0,37.6,0.191,30)

# changing the input data to a numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the numpy array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

# Standarized the input data
Standardized_data = Scaler.transform(input_data_reshaped)
print(Standardized_data)

prediction = classifier.predict(Standardized_data)
print(prediction)

[[ 0.04601433 -0.33690758  1.18414549 -1.28789107 -0.69289057  0.7117571
  -0.84881879 -0.27550725]]
[0]

c:\Users\Samyak\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
c:\Users\Samyak\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

In [25]:
if(prediction[0]==0):
    print("The peson is not diabetic")
else:
    print("The person is diabetic")

The peson is not diabetic

In [26]:
input_data = (1,102,74,0,0,39.5,0.293,42)

# changing the input data to a numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the numpy array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

# Standarized the input data
Standardized_data = Scaler.transform(input_data_reshaped)
print(Standardized_data)

prediction = classifier.predict(Standardized_data)
print(prediction)

if(prediction[0]==0):
    print("The peson is not diabetic")
else:
    print("The person is diabetic")

[[-0.84488505 -0.58696317  0.25347136 -1.28789107 -0.69289057  0.95290408
  -0.54079512  0.74584222]]
[0]
The peson is not diabetic

c:\Users\Samyak\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
c:\Users\Samyak\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

In [27]:
classifier.fit(X_train, Y_train)

SVC(kernel='linear')

In [28]:
Scaler = StandardScaler()
Scaler.fit(X_train)

X_train = Scaler.transform(X_train)
X_test = Scaler.transform(X_test)

In [29]:
print("Train Accuracy:", accuracy_score(Y_train, classifier.predict(X_train)))
print("Test Accuracy:", accuracy_score(Y_test, classifier.predict(X_test)))

Train Accuracy: 0.6368078175895765
Test Accuracy: 0.7077922077922078

c:\Users\Samyak\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
c:\Users\Samyak\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

In [30]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(n_estimators=100)
classifier.fit(X_train, Y_train)

RandomForestClassifier()

In [31]:
input_data = (11,120,80,37,150,42.3,0.785,48)

input_data_as_numpy_array = np.asarray(input_data)
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

Standardized_data = Scaler.transform(input_data_reshaped)

prediction = classifier.predict(Standardized_data)
print(prediction)

if(prediction[0]==0):
    print("The peson is not diabetic")
else:
    print("The person is diabetic")

[1]
The person is diabetic

c:\Users\Samyak\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [32]:
input_data = (2,99,60,17,160,36.6,0.453,21)

input_data_as_numpy_array = np.asarray(input_data)
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

Standardized_data = Scaler.transform(input_data_reshaped)

prediction = classifier.predict(Standardized_data)
print(prediction)

if(prediction[0]==0):
    print("The peson is not diabetic")
else:
    print("The person is diabetic")

[0]
The peson is not diabetic

c:\Users\Samyak\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [33]:
input_data =(0,181,88,44,510,43.3,0.222,26)

input_data_as_numpy_array =np.asarray(input_data)
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

Standardized_data =Scaler.transform(input_data_reshaped)

prediction = classifier.predict(Standardized_data)
print(prediction)

if(prediction[0]==0):
    print("This person is not diabetic")
else:
    print("This person is diabetic")

[1]
This person is diabetic

c:\Users\Samyak\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(